name: Check
    on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
   jobs:
     lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install deps
          run: npm ci
        - name: Lint
          run: npm run lint
      with:
        java-version: '17'
        distribution: 'temurin'
